### ISSUE TITLE
Make form for submitting ideas

### ISSUE THREAD

**Issue by charmaine** [charmaine/InternetWishlist#1]
Any kind of submission form will do :) Use your creativity and put the form under "submit" section in index.html

Make sure to read through the README of the repo :)

**Comment by vivekfyi** [comment]
@CharmaineLee : So this form has to be created using `typeform.com` right ?

**Comment by charmaine** [comment]
@vivex Yeah sure that would work. Feel free to make a Typeform account for the Internet Wishlist. I can definitely change the password for it later on! :) 

EDIT: It doesn't have to be Typeform though (just thought it would be easier)! I'll change the README to reflect that.

**Comment by vivekfyi** [comment]
any other suggestion than typeForm ?

**Comment by charmaine** [comment]
@vivex I believe a form connected to Google Sheets / Google Forms could be another way!

**Comment by Ernoff** [comment]
I will like to work on this issue
