### ISSUE TITLE
Area to Display Submitted Ideas

### ISSUE THREAD

**Issue by charmaine** [charmaine/InternetWishlist#5]
Make an area on the webpage to display submitted ideas after they have been submitted & approved. Developers will then have access to those ideas and work on them.

Make sure to read through the README first!

**Comment by suresach** [comment]
Hi @CharmaineLee Internet WishList seems interesting.
I'll be taking up this issue..fine? :)

**Comment by charmaine** [comment]
@suresach That would be awesome! Thanks :)

**Comment by suresach** [comment]
@CharmaineLee What do you prefer for showing ideas?
- kinda bulletin board
- accordions
- color flip boxes like [this](http://codepen.io/anon/pen/dpAQqQ)
- or the way we are showing successful projects
- anything else :)

**Comment by charmaine** [comment]
@suresach I think any of the first 3 would be awesome (the link for the color flip box doesn't work, but I think I know what you mean!) Feel free to take on whichever you personally like more / feel more comfortable working with. :) Thanks!

**Comment by suresach** [comment]
@CharmaineLee  that's awesome...I've fixed the link :)

**Comment by charmaine** [comment]
@suresach Perfect! Exactly what I thought! 👍
