### ISSUE TITLE
needs more memes

### ISSUE THREAD

**Issue by jsondoo** [charmaine/InternetWishlist#58]
needs more memes

**Comment by charmaine** [comment]
![meme](https://camo.githubusercontent.com/1b059e75d0fe430bd30b9c5ec2caaf35621caf58/68747470733a2f2f63646e2e6d656d652e616d2f696e7374616e6365732f36313730313330342e6a7067)

**Comment by charmaine** [comment]
Haha but all joking aside, feel free to spice this repo up with memes! ✨ I also love your `Mocking-Spongebob` repo 🙏
